name: npm publish

on:
  push:
    branches:
      - master
      - develop
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          LATEST=`npm view . version`
          CURRENT=`cat package.json | jq -r .version`
          if [ "$LATEST" != "$CURRENT" ]
          then
            npm ci
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@vs4vijay'
      # - run:  |
      #     LATEST=`npm view . version`
      #     CURRENT=`cat package.json | jq -r .version`
      #     if [ "$LATEST" != "$CURRENT" ]
      #     then
      #       npm ci
      #       npm publish --access public
      #     fi
      - name: Modify package.json to add @vs4vijay
        run: |
          node <<EOF
          const fs = require('fs').promises;
          fs.readFile('package.json', 'utf8').then((data) => JSON.parse(data)).then((json) => {
              json.name = '@$(echo "$GITHUB_REPOSITORY" | sed 's/\/.\+//')/' + json.name;
              console.info('Package name changed to %s', json.name);
              return fs.writeFile('package.json', JSON.stringify(json), 'utf8');
          }).catch(error => {
              console.error(error);
              process.exit(1);
          });
          EOF
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
